"""empty message

Revision ID: 579318267e25
Revises: 722bbfc9a5b9
Create Date: 2022-03-17 18:43:40.700760

"""

# revision identifiers, used by Alembic.
revision = "579318267e25"
down_revision = "722bbfc9a5b9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
