"""empty message

Revision ID: 722bbfc9a5b9
Revises: 84469d857dee
Create Date: 2022-03-17 17:15:59.196158

"""

# revision identifiers, used by Alembic.
revision = "722bbfc9a5b9"
down_revision = "84469d857dee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
